{
 "title": "Player Information Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "player_citizenid",
    "query": "SELECT CONCAT(\n         CONCAT(JSON_UNQUOTE(JSON_EXTRACT(charinfo, '$.firstname')), ' ', \n                JSON_UNQUOTE(JSON_EXTRACT(charinfo, '$.lastname'))),\n         ' [', citizenid, ']'\n       ) AS player_info\nFROM players \nORDER BY citizenid"
   }
  ]
 },
 "panels": [
  {
   "title": "Player Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "kifflom",
     "rawSql": "SELECT\n  CONCAT (\n    JSON_UNQUOTE (JSON_EXTRACT (p.charinfo, '$.firstname')),\n    ' ',\n    JSON_UNQUOTE (JSON_EXTRACT (p.charinfo, '$.lastname'))\n  ) AS playerName\nFROM\n  players p\nWHERE\n  p.citizenid = '${player_citizenid}'"
    }
   ]
  },
  {
   "title": "Citizen ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT citizenid FROM players WHERE citizenid = '${player_citizenid}'"
    }
   ]
  },
  {
   "title": "License ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT license FROM players WHERE citizenid = '${player_citizenid}'"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT \n  'Cash' as Type, JSON_UNQUOTE(JSON_EXTRACT(p.money, '$.cash')) as Amount \nFROM players p WHERE p.citizenid = '${player_citizenid}'\nUNION ALL\nSELECT \n  'Bank' as Type, JSON_UNQUOTE(JSON_EXTRACT(p.money, '$.bank')) as Amount \nFROM players p WHERE p.citizenid = '${player_citizenid}'\nUNION ALL\nSELECT \n  'Savings' as Type, 0 as Amount \nFROM players p WHERE p.citizenid = '${player_citizenid}'"
    }
   ]
  },
  {
   "title": "Player Details",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT \n  'Job' as `Key`, CONCAT(JSON_UNQUOTE(JSON_EXTRACT(p.job, '$.name')), ' (Grade: ', JSON_UNQUOTE(JSON_EXTRACT(p.job, '$.grade')), ')') as `Value` \nFROM players p \nWHERE p.citizenid = '${player_citizenid}'\nUNION ALL\nSELECT \n  'Gang' as `Key`, COALESCE(JSON_UNQUOTE(JSON_EXTRACT(p.gang, '$.label')), 'No Gang') as `Value` \nFROM players p \nWHERE p.citizenid = '${player_citizenid}'\nUNION ALL\nSELECT \n  'Nationality' as `Key`, JSON_UNQUOTE(JSON_EXTRACT(p.charinfo, '$.nationality')) as `Value` \nFROM players p WHERE p.citizenid = '${player_citizenid}'\nUNION ALL\nSELECT \n  'Phone' as `Key`, JSON_UNQUOTE(JSON_EXTRACT(p.charinfo, '$.phone')) as `Value` \nFROM players p WHERE p.citizenid = '${player_citizenid}'\nUNION ALL\nSELECT \n  'DOB' as `Key`, JSON_UNQUOTE(JSON_EXTRACT(p.charinfo, '$.birthdate')) as `Value` \nFROM players p WHERE p.citizenid = '${player_citizenid}'"
    }
   ]
  },
  {
   "title": "Properties",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n  p.id, \n  p.property_name as house \nFROM \n  properties p \nWHERE \n  p.owner = '${player_citizenid}' \nORDER BY \n  p.property_name;"
    }
   ]
  },
  {
   "title": "Player Vehicles",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT \n  v.plate as Plate,\n  v.vehicle as Vehicle,\n  v.garage as Garage,\n  v.state as State,\n  JSON_UNQUOTE(JSON_EXTRACT(v.mods, '$.fuelLevel')) as Fuel, \n  JSON_UNQUOTE(JSON_EXTRACT(v.mods, '$.engineHealth')) as Engine, \n  JSON_UNQUOTE(JSON_EXTRACT(v.mods, '$.bodyHealth')) as Body \nFROM \n  player_vehicles v\nJOIN \n  players p ON v.citizenid = p.citizenid \nWHERE \n  p.citizenid = '${player_citizenid}' \nORDER BY \n  v.vehicle;"
    }
   ]
  },
  {
   "title": "Inventory",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "dataset": "kifflom",
     "rawSql": "SELECT \n  FLOOR((CAST(JSON_UNQUOTE(JSON_EXTRACT(item_data, '$.slot')) AS UNSIGNED) - 1) / 5) as `row`,\n  (CAST(JSON_UNQUOTE(JSON_EXTRACT(item_data, '$.slot')) AS UNSIGNED) - 1) % 5 as `column`,\n  CONCAT(\n    JSON_UNQUOTE(JSON_EXTRACT(item_data, '$.name')), \n    ' - ', \n    JSON_UNQUOTE(JSON_EXTRACT(item_data, '$.count')), \n    'x'\n  ) as value\nFROM \n  kifflom.players,\n  JSON_TABLE(inventory, '$[*]' COLUMNS (\n    item_data JSON PATH '$'\n  )) as items\nWHERE \n  citizenid = '${player_citizenid}'\nORDER BY \n  `row`, `column`\nLIMIT 50"
    }
   ]
  },
  {
   "title": "Transaction History (Personal)",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT \n  FROM_UNIXTIME(JSON_EXTRACT(t.value, '$.time')) as Time, \n  JSON_EXTRACT(t.value, '$.trans_type') as Type, \n  JSON_EXTRACT(t.value, '$.title') as Title,\n  JSON_EXTRACT(t.value, '$.amount') as Amount, \n  JSON_EXTRACT(t.value, '$.message') as Message, \n  JSON_EXTRACT(t.value, '$.issuer') as Issuer, \n  JSON_EXTRACT(t.value, '$.receiver') as Receiver\nFROM \n  player_transactions pt, \n  JSON_TABLE(pt.transactions, '$[*]' COLUMNS(\n    value JSON PATH '$'\n  )) as t \nWHERE \n  pt.id = '${player_citizenid}' \nORDER BY \n  JSON_EXTRACT(t.value, '$.time') DESC \nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Sanctions",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT \n  FROM_UNIXTIME(b.timestamp) as date, \n  FROM_UNIXTIME(b.expire) as expires, \n  b.type as sanction, \n  b.reason, \n  b.bannedby as admin, \n  b.notes as note \nFROM \n  player_bans b \nJOIN \n  players p ON b.license = p.license \nWHERE \n  p.citizenid = '${player_citizenid}' \nORDER BY \n  b.timestamp DESC;"
    }
   ]
  }
 ]
}