name: Create Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ needs.build.outputs.artifact_name }}
        path: ./dist/
      
    - name: Create ZIP archive
      run: zip -r kifflom_log-${{ github.ref_name }}.zip ./dist/

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: kifflom_log-${{ github.ref_name }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}